{% set name = "ligo-raven" %}
{% set version = "3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ec7b818f8a0979d5cdbfa0e58b1533c7b612f41332b9be2168d62804db32f606
  patches:
    # clean up requirements
    - requirements.patch

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [win or py<38]

requirements:
  build:
    # for cross-compiling:
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
    - python                              # [build_platform != target_platform]
  host:
    - pip
    - python
    - setuptools
  run:
    - astropy
    - astropy-healpix
    - healpy !=1.12.0
    - gracedb-sdk
    - ligo.skymap >=0.1.1
    - numpy >=1.14.5
    - python
    - scipy >=0.7.2

test:
  requires:
    - pip
  imports:
    - ligo.raven
    - ligo.raven.gracedb_events
    - ligo.raven.search
  commands:
    # check requirements
    - python -m pip check
    # check scripts
    - raven_query --help
    - raven_search --help
    - raven_skymap_overlap --help
    - raven_coinc_far --help
    - raven_calc_signif_gracedb --help

about:
  home: https://git.ligo.org/lscsoft/raven/
  dev_url: https://git.ligo.org/lscsoft/raven.git
  doc_url: https://lscsoft.docs.ligo.org/raven/
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: COPYING
  summary: Low-latency coincidence search between external triggers and GW candidates
  description: |
    Low-latency coincidence search between external triggers and GW candidates

extra:
  recipe-maintainers:
    - bpiotrzkowski
    - duncanmmacleod
