{% set name = "ligo-raven" %}
{% set version = "1.10" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  # ligo-raven-1.8 on pypi only provides wheels, not a tarball,
  # so we build from the relevant git commit in the upstream repo.
  # Reported as: https://git.ligo.org/lscsoft/raven/issues/5
  git_url: https://git.ligo.org/lscsoft/raven.git
  git_tag: 7bcc36275d510d5c052d71baee1170b4375ff83c

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv "

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools
  run:
    - python >=3.6
    - h5py
    - healpy !=1.12.0
    - ligo-common
    - ligo-gracedb >=2.0.0
    - ligo-segments
    - ligo.skymap
    - lscsoft-glue
    - lxml
    - numpy >=1.14.5
    - python-lal
    - scipy >=0.7.2
    - voeventlib >=1.2

test:
  imports:
    - ligo.raven
    - ligo.raven.gracedb_events
    - ligo.raven.search
  commands:
    - raven_coinc_search_gracedb --help
    - raven_fetch_external_triggers --help
    - raven_file_cache_monitor --help
    - raven_gcn_web_scraper --help

about:
  home: https://git.ligo.org/lscsoft/raven/
  dev_url: https://git.ligo.org/lscsoft/raven/
  license: GPLv3+
  license_family: GPL
  license_file: COPYING
  summary: Low-latency coincidence search between external triggers and GW candidates
  description: |
    Low-latency coincidence search between external triggers and GW candidates

extra:
  recipe-maintainers:
    - duncanmmacleod
