{% set name = "ligo-raven" %}
{% set version = "2.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0a27a07bf92a8224ade7ece51e5024d21f4b38d505fe0414f6b27a4f3da651c9
  patches:
    # clean up requirements
    - requirements.patch

build:
  number: 0
  skip: true  # [win or py<38]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - h5py
    - healpy !=1.12.0
    - gracedb-sdk
    - ligo.skymap >=0.1.1
    - lscsoft-glue
    - lxml
    - numpy >=1.14.5
    - python
    - python-lal
    - scipy >=0.7.2
    - voeventlib >=1.2
  run_constrained:
    # the last version of ligo.skymap supported on python 3.7
    # isn't compatible with python-ligo-lw >=1.8.0
    - python-ligo-lw <1.8.0  # [py<38]

test:
  imports:
    - ligo.raven
    - ligo.raven.gracedb_events
    - ligo.raven.search
  commands:
    - raven_query --help
    - raven_search --help
    - raven_skymap_overlap --help
    - raven_coinc_far --help
    - raven_calc_signif_gracedb --help

about:
  home: https://git.ligo.org/lscsoft/raven/
  dev_url: https://git.ligo.org/lscsoft/raven/
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: COPYING
  summary: Low-latency coincidence search between external triggers and GW candidates
  description: |
    Low-latency coincidence search between external triggers and GW candidates

extra:
  recipe-maintainers:
    - duncanmmacleod
