{% set name = "ligo-raven" %}
{% set version = "1.16" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://git.ligo.org/lscsoft/raven/-/archive/v{{ version }}/raven-v{{ version }}.tar.gz
  sha256: c3f8f70d7f35ca19876bda27337a62884fc9ec759a326d6e1425b6b472de765a

build:
  number: 0
  skip: true  # [win or py<35]
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv "

requirements:
  host:
    - python
    - pip
    - setuptools
  run:
    - python
    - h5py
    - healpy !=1.12.0
    - ligo-common
    - ligo-gracedb >=2.0.0
    - ligo-segments
    - ligo.skymap >=0.1.1
    - lscsoft-glue
    - lxml
    - numpy >=1.14.5
    - python-lal
    - scipy >=0.7.2
    - voeventlib >=1.2

test:
  imports:
    - ligo.raven
    - ligo.raven.gracedb_events
    - ligo.raven.search
  commands:
    - raven_coinc_search_gracedb --help
    - raven_fetch_external_triggers --help
    - raven_file_cache_monitor --help
    - raven_gcn_web_scraper --help

about:
  home: https://git.ligo.org/lscsoft/raven/
  dev_url: https://git.ligo.org/lscsoft/raven/
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: COPYING
  summary: Low-latency coincidence search between external triggers and GW candidates
  description: |
    Low-latency coincidence search between external triggers and GW candidates

extra:
  recipe-maintainers:
    - duncanmmacleod
