{% set name = "ligo-raven" %}
{% set version = "2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 1078466f7868a8cf5ab67ba094bc3d825413894f84b9c4e2e18d9abb8aa66ff6

build:
  number: 0
  skip: true  # [win]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - pytest-runner
    - python
    - setuptools
  run:
    - astropy
    - astropy-healpix
    - gracedb-sdk
    - healpy !=1.12.0
    - ligo.skymap >=0.1.1
    - lscsoft-glue
    - lxml
    - matplotlib-base
    - numpy >=1.14.5
    - python
    - python-lal
    - scipy >=0.7.2
    - voeventlib >=1.2

test:
  requires:
    - pip
    - pytest
  commands:
    # check requirements
    - python -m pip check
    # run test suite
    - python -m pytest -ra --pyargs ligo.tests
    # sanity check scripts
    - raven_query --help
    - raven_search --help
    - raven_skymap_overlap --help
    - raven_coinc_far --help
    - raven_calc_signif_gracedb --help

about:
  home: https://git.ligo.org/lscsoft/raven/
  dev_url: https://git.ligo.org/lscsoft/raven/
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: COPYING
  summary: Low-latency coincidence search between external triggers and GW candidates
  description: |
    RAVEN is used in the LVK low-latency alert system in order to find associations
    between gravitational waves and other astronomical transients via GraceDb.
    See the following for more details:

    - <https://igwn.readthedocs.io/projects/gwcelery/en/latest/gwcelery.tasks.external_triggers.html>
    - <https://igwn.readthedocs.io/projects/gwcelery/en/latest/gwcelery.tasks.raven.html>

    RAVEN is also designed to be able to perform these tasks via GraceDb in offline searches
    as well.

extra:
  recipe-maintainers:
    - duncanmmacleod
