{% set name = "ligo-raven" %}
{% set version = "1.18" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2336a0e95b132f63443712a0d1fbab2810bff21f2f36398d2b4168a5b2293900

build:
  number: 0
  skip: true  # [win or py<36]
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - pytest-runner
    - python
    - setuptools
  run:
    - h5py
    - healpy !=1.12.0
    - ligo-common
    - ligo-gracedb >=2.2.0
    - ligo-segments
    - ligo.skymap >=0.1.1
    - lscsoft-glue
    - lxml
    - numpy >=1.14.5
    - python
    - python-lal
    - scipy >=0.7.2
    - voeventlib >=1.2

test:
  imports:
    - ligo.raven
    - ligo.raven.gracedb_events
    - ligo.raven.search
  commands:
    - raven_coinc_search_gracedb --help
    - raven_fetch_external_triggers --help
    - raven_file_cache_monitor --help
    - raven_gcn_web_scraper --help

about:
  home: https://git.ligo.org/lscsoft/raven/
  dev_url: https://git.ligo.org/lscsoft/raven/
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: COPYING
  summary: Low-latency coincidence search between external triggers and GW candidates
  description: |
    Low-latency coincidence search between external triggers and GW candidates

extra:
  recipe-maintainers:
    - duncanmmacleod
