travis:
  secure:
    BINSTAR_TOKEN: rWdO3xFIbmWbRHqnYIjeyU5AFFV6dCTfxqOyr6zK7UtfSXGSbwLM0Ha6O/0nWlcvf51EsdfUz9ZqwlAJ2X8SI1KVvNP+zVwB9661bjGcI93BvSk1uAOV7hfuvzKuOK5wSi4WzVIo3AwB3B7vRseelSSsZXcCJQNHKRETJomFxVkLdKXJNIsiTLo2hKmNxZOFudgREV9IZ09nuXcEXl4gJcC7Xz38iY32pGOuDK8kX0TIN9RMHMFtae7M7bBUva9qbjUUS1/idJ/nsYmYqvv4+lqPrrOFHZcf1NTOmU0PUQAHAfzpnvZ5QsNlid8PCSO81yjL/+G7+iIl+cFNLOhJ5h3qijN6Rjr1vh5P9wO4Cm1l2J6Dr7tumw+iNR1PyRJMDY8jEwWcSi6C4qiAZipKRqlQ2xbNMODDbAiot0xbcNdfXwVKFZu9PEb/APlzto/0S42sVKd5xjC3OBtnS4diqVGJKAJ9A9NlmdeeO/UzVMnFUlAPeknTBE1s3YA4EFHS5wpL1guHNlwEKKqYANepqspAz2RDvKrd/KHad0akqawaiw8exu5Duv+7gkkd9+LVKdUSOa9PaM2223sQwqJbhvBJKm8J48psgEIBPBR1bLum2rvYGDLcXsZ17cvUH+r6DonNAQaOizu9qV3HfJ/MHARApQ84mcHRMKjBuldjflQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
